services:
  habittracker-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: habittracker-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ./data:/app/data
    networks:
      - habittracker-network

networks:
  habittracker-network:
    driver: bridge